version: "3.9"

services:
  redis:
    image: redis:7
    container_name: ig_manager_redis
    ports:
      - "6379:6379"

  worker:
    image: python:3.11-slim
    container_name: ig_manager_worker
    working_dir: /app
    env_file: .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
      python -m app.workers.post_worker"

  dm_worker:
    image: python:3.11-slim
    container_name: ig_manager_dm_worker
    working_dir: /app
    env_file: .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
      python -m app.workers.dm_worker"
